### ISSUE TITLE
add POST: feedback

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/public-api#13]
as a player i want to send feedback to the plugin
- add db table
- add db model
- add endpoint (given that the volume is low we may want to directly insert into the db)

**Comment by extreme4all** [comment]
```
-- playerdata.PredictionsFeedback definition

CREATE TABLE `PredictionsFeedback` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `voter_id` int NOT NULL,
  `subject_id` int NOT NULL,
  `prediction` varchar(50) NOT NULL,
  `confidence` float NOT NULL,
  `vote` int NOT NULL DEFAULT '0',
  `feedback_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `reviewed` tinyint NOT NULL DEFAULT '0',
  `reviewer_id` int DEFAULT NULL,
  `user_notified` tinyint NOT NULL DEFAULT '0',
  `proposed_label` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Unique_Vote` (`prediction`,`subject_id`,`voter_id`) USING BTREE,
  KEY `Voter_ID` (`voter_id`),
  KEY `Subject_ID` (`subject_id`),
  KEY `Reviewer_ID` (`reviewer_id`),
  CONSTRAINT `Reviewer_ID` FOREIGN KEY (`reviewer_id`) REFERENCES `Tokens` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `Subject_ID` FOREIGN KEY (`subject_id`) REFERENCES `Players` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `Voter_ID` FOREIGN KEY (`voter_id`) REFERENCES `Players` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);
```

**Comment by extreme4all** [comment]
incoming data:
```
{
  "player_name": "string",
  "vote": 0,
  "prediction": "string",
  "confidence": 0,
  "subject_id": 0,
  "feedback_text": "string",
  "proposed_label": "string"
}
```

**Comment by RusticPotatoes** [comment]
> ```
> -- playerdata.PredictionsFeedback definition
> 
> CREATE TABLE `PredictionsFeedback` (
>   `id` int NOT NULL AUTO_INCREMENT,
>   `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
>   `voter_id` int NOT NULL,
>   `subject_id` int NOT NULL,
>   `prediction` varchar(50) NOT NULL,
>   `confidence` float NOT NULL,
>   `vote` int NOT NULL DEFAULT '0',
>   `feedback_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
>   `reviewed` tinyint NOT NULL DEFAULT '0',
>   `reviewer_id` int DEFAULT NULL,
>   `user_notified` tinyint NOT NULL DEFAULT '0',
>   `proposed_label` varchar(50) DEFAULT NULL,
>   PRIMARY KEY (`id`),
>   UNIQUE KEY `Unique_Vote` (`prediction`,`subject_id`,`voter_id`) USING BTREE,
>   KEY `Voter_ID` (`voter_id`),
>   KEY `Subject_ID` (`subject_id`),
>   KEY `Reviewer_ID` (`reviewer_id`),
>   CONSTRAINT `Reviewer_ID` FOREIGN KEY (`reviewer_id`) REFERENCES `Tokens` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
>   CONSTRAINT `Subject_ID` FOREIGN KEY (`subject_id`) REFERENCES `Players` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
>   CONSTRAINT `Voter_ID` FOREIGN KEY (`voter_id`) REFERENCES `Players` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
> );
> ```

is this line for tokens still needed?
```mysql
    CONSTRAINT Reviewer_ID FOREIGN KEY (reviewer_id) REFERENCES Tokens (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
```

**Comment by extreme4all** [comment]
i think we can drop that, we don't use the reviewer functionality

**Comment by extreme4all** [comment]
the playername can be "anonymoususer ef33564c e7fe 46e4 8768 dc777cbcddd6"
